# Makefile, um aus den UDO Quellendir STG und HTML Dateien zu
# generieren.
# Die Konvertierung der Dokumente, die nur einen Teil des Textes umfassen,
# wird ueber den Auruf der Bash mit Kommandozeile und explizitem Setzen
# des Returnwertes von 0 gemacht. Da bei diesen Teilen einige Querverweise
# nicht verlinkt werden koennen, wuerde UDO mit einem Returnwert <>0
# enden und das make abbrechen, obwohl dies nicht erwuenscht ist.


HTMLPATH=html
STGPATH=stguide
HTMLFILE=$(HTMLPATH)/index.html
HTMLUFLAGS=-h -o $(HTMLFILE)
STGFLAGS=-s

LINEAPATH=linea

XBIOSPATH=xbios
XBIOS_BILDSCRM_PATH=bildscrm
XBIOS_CENTSCRN_PATH=centscrn
XBIOS_CRAZYDOT_PATH=crazydot
XBIOS_CT60_PATH=ct60
XBIOS_DATETIME_PATH=datetime
XBIOS_DRUCKER_PATH=drucker
XBIOS_DSP56001_PATH=dsp56001
XBIOS_INTERRPT_PATH=interrpt
XBIOS_LAUFWERK_PATH=laufwerk
XBIOS_OVERSCAN_PATH=overscan
XBIOS_PCI_BIOS_PATH=pci_bios
XBIOS_INTRFACE_PATH=intrface
XBIOS_SOUND_PATH=sound
XBIOS_STARTRAC_PATH=startrac
XBIOS_SPEZIAL_PATH=spezial
XBIOS_TASTATUR_PATH=tastatur

LINEAFILES=$(LINEAPATH)/linea.u $(LINEAPATH)/init.ui $(LINEAPATH)/putpixel.ui \
	$(LINEAPATH)/getpixel.ui $(LINEAPATH)/line.ui $(LINEAPATH)/hline.ui \
	$(LINEAPATH)/fillrect.ui $(LINEAPATH)/fillpoly.ui \
	$(LINEAPATH)/bitblt.ui $(LINEAPATH)/textblt.ui \
	$(LINEAPATH)/shmouse.ui $(LINEAPATH)/hdmouse.ui \
	$(LINEAPATH)/trmouse.ui $(LINEAPATH)/udrsprit.ui \
	$(LINEAPATH)/drsprite.ui $(LINEAPATH)/cpraster.ui \
	$(LINEAPATH)/seedfill.ui

XBIOS_BILDSCRM_FILES=$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/cursconf.ui\
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/egetpale.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/egetshif.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/esetbank.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/esetcolo.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/esetgray.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/esetpale.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/esetshif.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/esetsmea.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/getrez.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/initmous.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/logbase.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/mon_type.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/physbase.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/setcolor.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/setpalet.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/setscree.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/vgetrgb.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/vsetscre.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/vgetsize.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/vsetmask.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/vsetmode.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/vsetrgb.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/vsetsync.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/vsync.ui \
	$(XBIOSPATH)/$(XBIOS_BILDSCRM_PATH)/bildscrm.ui

XBIOS_CENTSCRN_FILES=$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/multimon.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/setmon.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/sizecomp.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vattrib.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vclose.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vcreate.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vdelete.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vfirst.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vload.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vlock.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vnext.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/voffset.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vopen.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vread.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vsave.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vscroll.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vseek.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vsize.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vvalid.ui \
	$(XBIOSPATH)/$(XBIOS_CENTSCRN_PATH)/vwrite.ui \

XBIOS_CRAZYDOT_FILES=$(XBIOSPATH)/$(XBIOS_CRAZYDOT_PATH)/gscrdesc.ui \
	$(XBIOSPATH)/$(XBIOS_CRAZYDOT_PATH)/resetscr.ui \
	$(XBIOSPATH)/$(XBIOS_CRAZYDOT_PATH)/getnofpm.ui \
	$(XBIOSPATH)/$(XBIOS_CRAZYDOT_PATH)/getpmode.ui \
	$(XBIOSPATH)/$(XBIOS_CRAZYDOT_PATH)/readmode.ui \
	$(XBIOSPATH)/$(XBIOS_CRAZYDOT_PATH)/cpmd2amd.ui \
	$(XBIOSPATH)/$(XBIOS_CRAZYDOT_PATH)/acmodenr.ui \
	$(XBIOSPATH)/$(XBIOS_CRAZYDOT_PATH)/gamddesc.ui \
	$(XBIOSPATH)/$(XBIOS_CRAZYDOT_PATH)/gregbase.ui \
	$(XBIOSPATH)/$(XBIOS_CRAZYDOT_PATH)/getfeat.ui \
	$(XBIOSPATH)/$(XBIOS_CRAZYDOT_PATH)/getafeat.ui

XBIOS_CT60_FILES=$(XBIOSPATH)/$(XBIOS_CT60_PATH)/rcortemp.ui \
	$(XBIOSPATH)/$(XBIOS_CT60_PATH)/rd_param.ui \
	$(XBIOSPATH)/$(XBIOS_CT60_PATH)/cache.ui \
	$(XBIOSPATH)/$(XBIOS_CT60_PATH)/fl_cache.ui

XBIOS_DATETIME_FILES=$(XBIOSPATH)/$(XBIOS_DATETIME_PATH)/gettime.ui \
	$(XBIOSPATH)/$(XBIOS_DATETIME_PATH)/nvmacces.ui \
	$(XBIOSPATH)/$(XBIOS_DATETIME_PATH)/settime.ui \
	$(XBIOSPATH)/$(XBIOS_DATETIME_PATH)/xbtimer.ui \
	$(XBIOSPATH)/$(XBIOS_DATETIME_PATH)/datetime.ui

XBIOS_DRUCKER_FILES=$(XBIOSPATH)/$(XBIOS_DRUCKER_PATH)/prtblk.ui \
	$(XBIOSPATH)/$(XBIOS_DRUCKER_PATH)/scrdmp.ui \
	$(XBIOSPATH)/$(XBIOS_DRUCKER_PATH)/setprt.ui

XBIOS_DSP56001_FILES=$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/availabl.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/blkbytes.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/blkhndsh.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/blkunpac.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/blkwords.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/doblock.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/execboot.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/execprog.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/flushsub.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/getproga.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/getwords.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/hf0.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/hf1.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/hf2.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/hf3.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/hstat.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/inqsubra.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/instream.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/iostream.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/loadprog.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/loadsubr.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/lock.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/lodtobin.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/multbloc.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/outstrea.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/removein.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/requestu.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/reserve.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/runsubro.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/setvecto.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/triggerh.ui \
	$(XBIOSPATH)/$(XBIOS_DSP56001_PATH)/unlock.ui

XBIOS_INTERRPT_FILES=$(XBIOSPATH)/$(XBIOS_INTERRPT_PATH)/jdisint.ui \
	$(XBIOSPATH)/$(XBIOS_INTERRPT_PATH)/jenabint.ui

XBIOS_LAUFWERK_FILES=$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/dmaread.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/dmawrite.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/flopfmt.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/floprate.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/floprd.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/flopver.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/flopwr.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/metaclos.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/metadinf.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/metagett.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/metainit.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/metaioct.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/metaopen.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/metaread.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/metasets.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/metastar.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/metastat.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/metastop.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/metawrit.ui \
	$(XBIOSPATH)/$(XBIOS_LAUFWERK_PATH)/protobt.ui

XBIOS_OVERSCAN_FILES=$(XBIOSPATH)/$(XBIOS_OVERSCAN_PATH)/oscanis.ui \
	$(XBIOSPATH)/$(XBIOS_OVERSCAN_PATH)/oscanpat.ui \
	$(XBIOSPATH)/$(XBIOS_OVERSCAN_PATH)/oscanphy.ui \
	$(XBIOSPATH)/$(XBIOS_OVERSCAN_PATH)/oscanscr.ui \
	$(XBIOSPATH)/$(XBIOS_OVERSCAN_PATH)/oscanswi.ui \
	$(XBIOSPATH)/$(XBIOS_OVERSCAN_PATH)/oscantab.ui \
	$(XBIOSPATH)/$(XBIOS_OVERSCAN_PATH)/oscanvb.ui

XBIOS_PCI_BIOS_FILES=$(XBIOSPATH)/$(XBIOS_PCI_BIOS_PATH)/fpdevice.ui \
	$(XBIOSPATH)/$(XBIOS_PCI_BIOS_PATH)/fpclassc.ui

XBIOS_INTRFACE_FILES=$(XBIOSPATH)/$(XBIOS_INTRFACE_PATH)/bconmap.ui \
	$(XBIOSPATH)/$(XBIOS_INTRFACE_PATH)/dosound.ui \
	$(XBIOSPATH)/$(XBIOS_INTRFACE_PATH)/extrscon.ui \
	$(XBIOSPATH)/$(XBIOS_INTRFACE_PATH)/giaccess.ui \
	$(XBIOSPATH)/$(XBIOS_INTRFACE_PATH)/ikbdws.ui \
	$(XBIOSPATH)/$(XBIOS_INTRFACE_PATH)/iorec.ui \
	$(XBIOSPATH)/$(XBIOS_INTRFACE_PATH)/kbdvbase.ui \
	$(XBIOSPATH)/$(XBIOS_INTRFACE_PATH)/mfpint.ui \
	$(XBIOSPATH)/$(XBIOS_INTRFACE_PATH)/midiws.ui \
	$(XBIOSPATH)/$(XBIOS_INTRFACE_PATH)/offgibit.ui \
	$(XBIOSPATH)/$(XBIOS_INTRFACE_PATH)/ongibit.ui \
	$(XBIOSPATH)/$(XBIOS_INTRFACE_PATH)/rsconf.ui \

XBIOS_SOUND_FILES=$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/buffoper.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/buffptr.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/devconne.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/dsptrist.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/gpio.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/locksnd.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/setbuffe.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/setinter.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/setmode.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/setmontr.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/settrack.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/sndstatu.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/soundcmd.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/startrac.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/unlocksn.ui \
	$(XBIOSPATH)/$(XBIOS_SOUND_PATH)/waveplay.ui

XBIOS_STARTRAC_FILES=$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/installe.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/cardslot.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/cardsel.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/cardmagi.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/cardadr.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/digana.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/digcom.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/dspmode.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/sclock.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/highsrat.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/bypass.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/recmode.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/playmode.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/mode24.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/digmode.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/scmsmode.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/mycopybi.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/emphasis.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/digsrate.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/digcode.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/errorcod.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/cblmode.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/cblread.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/recstat.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/playstat.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/volad.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/volda.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/readsmp.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/writesmp.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/intact.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/dspintac.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/sysreset.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/dspreset.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/dspmemor.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/clkdivid.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/pathset.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/dsp_host.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/dspclear.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/mix.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/dspmix.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/monitor.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/recwait.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/memrec.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/memplay.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/recplay.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/hardrec.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/hardplay.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/hrecplay.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_pea.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_ime.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_ipl.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_ipm.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_hre.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_hpl.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_hpm.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_mrp.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_mpp.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_mpk.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_hrp.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_hpp.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_hpk.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_xmr.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_xmp.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_xxp.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_xr4.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/init_xp4.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/peakshak.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/read_rlo.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/read_rhi.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/read_rds.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/read_rae.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/read_rin.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/wr_rlow.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/wr_rhi.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/wr_rdsp.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/wr_raes.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/wr_rint.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/read_dp1.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/read_dp2.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/read_dpo.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/read_dco.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/read_dpd.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/read_dcl.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/wr_dpat1.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/wr_dpat2.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/wr_dport.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/wr_dconv.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/wr_dpdat.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/wr_dclk.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/fastcut.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/peaksuch.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/zerono.ui \
	$(XBIOSPATH)/$(XBIOS_STARTRAC_PATH)/fading.ui

XBIOS_SPEZIAL_FILES=$(XBIOSPATH)/$(XBIOS_SPEZIAL_PATH)/blitmode.ui \
	$(XBIOSPATH)/$(XBIOS_SPEZIAL_PATH)/cachectr.ui \
	$(XBIOSPATH)/$(XBIOS_SPEZIAL_PATH)/cjar.ui \
	$(XBIOSPATH)/$(XBIOS_SPEZIAL_PATH)/dbmsg.ui \
	$(XBIOSPATH)/$(XBIOS_SPEZIAL_PATH)/janus.ui \
	$(XBIOSPATH)/$(XBIOS_SPEZIAL_PATH)/puntaes.ui \
	$(XBIOSPATH)/$(XBIOS_SPEZIAL_PATH)/random.ui \
	$(XBIOSPATH)/$(XBIOS_SPEZIAL_PATH)/ssbrk.ui \
	$(XBIOSPATH)/$(XBIOS_SPEZIAL_PATH)/supexec.ui \
	$(XBIOSPATH)/$(XBIOS_SPEZIAL_PATH)/trapper.ui \
	$(XBIOSPATH)/$(XBIOS_SPEZIAL_PATH)/wdgctrl.ui

XBIOS_TASTATUR_FILES=$(XBIOSPATH)/$(XBIOS_TASTATUR_PATH)/bioskeys.ui \
	$(XBIOSPATH)/$(XBIOS_TASTATUR_PATH)/kbrate.ui \
	$(XBIOSPATH)/$(XBIOS_TASTATUR_PATH)/keytbl.ui

XBIOSFILES=$(XBIOSPATH)/xbios.u $(XBIOSPATH)/struktur.ui \
	$(XBIOSPATH)/xbios_f.u $(XBIOS_BILDSCRM_FILES) \
	$(XBIOS_CENTSCRN_FILES) $(XBIOS_CRAZYDOT_FILES) $(XBIOS_CT60_FILES) \
	$(XBIOS_DATETIME_FILES) $(XBIOS_DRUCKER_FILES) \
	$(XBIOS_DSP56001_FILES) $(XBIOS_INTERRPT_FILES) \
	$(XBIOS_LAUFWERK_FILES) $(XBIOS_OVERSCAN_FILES)	\
	$(XBIOS_PCI_BIOS_FILES) $(XBIOS_INTRFACE_FILES) $(XBIOS_SOUND_FILES) \
	$(XBIOS_STARTRAC_FILES) $(XBIOS_SPEZIAL_FILES) $(XBIOS_TASTATUR_FILES)

#
all: $(STGPATH)/linea.stg $(STGPATH)/xbios.stg

#
$(STGPATH)/linea.stg: e_linea.u $(LINEAFILES)
	bash -c "udo $(STGFLAGS) -o $(STGPATH)/linea.stg e_linea.u; exit 0"

#
$(STGPATH)/xbios.stg: e_xbios.u $(XBIOSFILES)
	bash -c "udo $(STGFLAGS) -o $(STGPATH)/xbios.stg e_xbios.u; exit 0"

#
clean:
	rm $(STGPATH)/*
	rm $(HTMLPATH)/*
